### ISSUE TITLE
为什么开始训练后就立即停止了也没有报错

### ISSUE THREAD

**Issue by zhangxy22** [rui9812/GoldE#1]
为什么开始训练后就立即停止了也没有报错

**Comment by rui9812** [comment]
Hi zhangxy22,

The default training mode is set to "_nohup_" (see run.sh), which means you can find the current training output in the _logs_ folder. If you want the output to be displayed in the frontend instead, please remove "_nohup_" from line 41 and "_> ./$LOG.log 2>&1 &_" from line 52 in run.sh.

**Comment by zhangxy22** [comment]
我已经解决这个问题了，我想知道在训练的过程中能不能合成新的三元组进行训练我看你在训练中已经引入了负样本。第二个我不确定这里的打分函数是什么 能否用于类比检索器 检索实体进行类比学习

在 2024-10-06 20:06:49，Rui Li ***@***.***> 写道：

Hi zhangxy22,
The default training mode is set to "nohup" (see run.sh), which means you can find the current training output in the logs folder. If you want the output to be displayed in the frontend instead, please remove "nohup" from line 41 and "> ./$LOG.log 2>&1 &" from line 52 in run.sh.

**Comment by rui9812** [comment]
Hi @zhangxy22,

1. 在训练的过程中能不能合成新的三元组进行训练我看你在训练中已经引入了负样本
I'm not sure if I fully understand your point. If you are referring to data augmentation (increasing the number of positive samples or selecting more challenging negative samples), this is indeed a potentially effective way to improve the performance of KGE models.
2. 打分函数是什么
The scoring function here measures the distance between the entity transformed by the relation and the candidates (the closer they are, the higher the plausibility score of the candidate entity).

Thanks for your questions and attention.

Best Regards

**Comment by zhangxy22** [comment]
thank you for your help.your suggestion is very important，i want give you my kiss，love you

在 2024-10-06 20:40:26，Rui Li ***@***.***> 写道：

Hi @zhangxy22,
在训练的过程中能不能合成新的三元组进行训练我看你在训练中已经引入了负样本
 I'm not sure if I fully understand your point. If you are referring to data augmentation (increasing the number of positive samples or selecting more challenging negative samples), this is indeed a potentially effective way to improve the performance of KGE models. 打分函数是什么
 The scoring function here measures the distance between the entity transformed by the relation and the candidates (the closer they are, the higher the plausibility score of the candidate entity).Thanks for your questions and attention.
Best Regards

**Comment by zhangxy22** [comment]
do you have video to teach me your paper
